**Numpy**
* Numpy -> Numerical Python
* pip install numpy ile numpy kütüphanesini yüklemeli, kurulumunu tamamlamalıyız.

In [3]:
import numpy as np

* Numpy ndarray Nesnesi

In [4]:
nd = np.array([1, 2, 3, 4, 5, 6, 7])
print(nd) #diziyi yazdırdık
print(type(nd)) #nd dizisinin tipini öğrendik

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [5]:
nd = np.array((1, 2, 3, 4, 5, 6, 7)) #tuple şeklinde de yazabiliriz
print(nd)

[1 2 3 4 5 6 7]


* Dizilerde Boyutlar

In [6]:
#0 - Boyutlu Dizi
nd = np.array(35)

print(nd)

35


In [8]:
#1 - Boyutlu Dizi
nd = np.array([1,2,3])
print(nd)

[1 2 3]


In [10]:
#2 - Boyutlu Dizi
nd2 = np.array([[1,2,3],[4,5,6]])
print(nd2)

[[1 2 3]
 [4 5 6]]


In [11]:
# 3 - Boyutlu Dizi
nd3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] )
print(nd3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
#Dizinin boyutunu alma öğrenme
print(nd3.ndim)
print(nd2.ndim)

3
2


In [14]:
#Çok boyutlu diziler

nd = np.array([1,2,3],ndmin=2)
print(nd)
print(nd.ndim)

[[1 2 3]]
2


In [15]:
#Dizinin satır ve sütun bilgilerini alma
nd = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]] )
print(nd.shape)

(2, 2, 3)


In [21]:
nd = np.array([1,2,3,4,5,6,7,8,9,0])
print(nd.shape)

(10,)


In [26]:
print(nd.reshape(5,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
[1 2 3 4 5 6 7 8 9 0]


In [28]:
#arange()
nd = np.arange(0,10,2)
print(nd)

[0 2 4 6 8]


In [29]:
#Dizi elemanlarına erişim
nd = np.array([1,2,3,4,5])
print(nd[2])

3


In [41]:
nd2 = np.array([[1,2,3],[4,5,6]])
print(nd2[1,2])
print(nd2[0,-1])

6
3


In [42]:
nd = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(nd)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [46]:
print(nd[0, 1, 2])

6


* Numpy Slicing İşlemi

In [47]:
nd = np.array([1,2,3,4,5,6,7,8])
print(nd[:4])

[1 2 3 4]


In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.random.random((4,5)) #0 ile 1 aralığında sayılar oluşturuldu

array([[0.86799757, 0.78793911, 0.8030423 , 0.70809222, 0.35779782],
       [0.79177477, 0.1756136 , 0.59344161, 0.57953509, 0.9132501 ],
       [0.99345244, 0.25971234, 0.51365149, 0.58727956, 0.93611822],
       [0.71153865, 0.87737806, 0.67599226, 0.52562164, 0.9448219 ]])

In [53]:
np.random.random((2,3))

array([[0.51348828, 0.19801007, 0.71962272],
       [0.83620032, 0.27087335, 0.59685674]])

In [56]:
np.linspace(4,5,num = 5) #eşit oranda aralık olur

array([4.  , 4.25, 4.5 , 4.75, 5.  ])

In [58]:
np.linspace(4, 5, 5, endpoint=False) #sondaki değer ekrana yazdırılmaz

array([4. , 4.2, 4.4, 4.6, 4.8])

In [60]:
np.full((2, 3), 8) #2 satır 3 sütunluk 8lerden oluşan bir array matrisi

array([[8, 8, 8],
       [8, 8, 8]])

In [62]:
#matris birleştirme
nd1 = np.array([1, 2, 3])
nd2 = np.array([4, 5, 6])

nd3 = np.concatenate([nd1,nd2])
print(nd3)

[1 2 3 4 5 6]


In [63]:
my_list = [1, 2, 3]
nd2 = np.array([4, 5, 6])

nd3 = np.concatenate([my_list,nd2])
print(nd3)

[1 2 3 4 5 6]
